# Generated by Django 3.2.9 on 2021-11-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='Phone No.',
            field=models.CharField(max_length=15, null=True, verbose_name='phone'),
        ),
    ]
