# Generated by Django 3.2.9 on 2021-11-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20211129_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Phone No.',
        ),
    ]
